# This is a basic workflow to help you get started with Actions

name: Testing on FreeBSD

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [master]
  pull_request:
    branches:
         - '*'
env:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_on_freebsd:
    runs-on: ubuntu-latest
    name: A job to run test in FreeBSD
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v5
      # Runs a single command using the runners shell
      - name: build and run tests packages on FreeBSD
        id: test_freebsd
        uses: vmactions/freebsd-vm@v1
        with:
            release: "15.0"
            prepare: |
                pkg update -f
                pkg upgrade -y
                pkg install -y gmake autoconf automake libtool pkgconf perl5 git
                pkg install -y graphicsmagick pstoedit png gettext-tools intltool glib p5-XML-Parser
            run: |
                ./autogen.sh
                ./configure
                gmake
                gmake check
